parameters:
    db:   '%budby_mongodb.db%'
    host: '%budby_mongodb.host%'

services:
    budby_mongodb.manager:
        class: Budby\MongoDbBundle\Manager\BudbyMongoDbManager
        calls:
            - [ setConfigData, [ '%db%', '%host%' ] ]
